name: Benchmark

on:
    push:
        branches:
            - main

jobs:
    run-benchmarks:
        runs-on:  ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install  Rust
              uses: dtolnay/rust-toolchain@stable
            - name: Install Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.21.1'
            - name: Install crystal
              uses: crystal-lang/install-crystal@v1
            - name: Install zig
              uses: goto-bus-stop/setup-zig@v2
            - name: Install Julia
              uses: julia-actions/setup-julia@v1
            - name: Install hyperfine for benchmarking
              run: cargo install hyperfine
            - name: Run Benchmark
              run: ./run.sh all
